language: java
jdk:
 - openjdk13

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -mihailbichkov@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
    
env:
    global:
    - CODECOV_TOKEN="724ade4b-8049-470a-b2d4-2d40f4f4e703"